(function () {
  "use strict";
  if (window.location.search || window.location.hash) return;
  var url = "https://wqrjdyfiokrvfgosseky.supabase.co";
  var key = "sb_publishable_77F7Fv7KzbgWv3AAm-vm9w_4B3BCSbs";
  var root = document.getElementById("root");
  if (!root) return;
  var css = document.createElement("style");
  css.textContent = "#ssuk-hub-shell{position:relative;z-index:20;min-height:100vh;background:#f7faf6;color:#21483f;font-family:Pretendard,'Noto Sans KR',Arial,sans-serif}#ssuk-hub-shell *{box-sizing:border-box}.ssuk-hub-bar{display:flex;justify-content:space-between;align-items:center;max-width:1200px;margin:auto;padding:22px 28px;border-bottom:1px solid #dfe8e1}.ssuk-hub-bar strong{display:block;font-size:20px}.ssuk-hub-bar span{display:block;margin-top:4px;color:#718078;font-size:12px}.ssuk-hub-bar button,.ssuk-hub-reset{border:1px solid #28594f;border-radius:8px;background:#28594f;color:#fff;padding:10px 14px;font-weight:700;cursor:pointer}.ssuk-hub-main{max-width:1200px;margin:auto;padding:56px 28px}.ssuk-hub-intro span,.ssuk-hub-section-head span{color:#5a8476;font-size:11px;font-weight:800;letter-spacing:2px}.ssuk-hub-intro h1{margin:10px 0 8px;font-size:34px}.ssuk-hub-intro p{margin:0;color:#718078}.ssuk-hub-layout{display:grid;grid-template-columns:280px 1fr;gap:36px;margin-top:46px}.ssuk-hub-layout aside,.ssuk-hub-classes{min-width:0}.ssuk-hub-layout h2{margin:0 0 16px;font-size:18px}.ssuk-hub-school-list{display:grid;gap:8px}.ssuk-hub-school{display:block;text-align:left;border:1px solid #d7e3da;border-radius:8px;background:#fff;padding:14px;cursor:pointer}.ssuk-hub-school.active{border-color:#508271;background:#eaf2ed}.ssuk-hub-school span,.ssuk-hub-school small{display:block}.ssuk-hub-school span{font-weight:750}.ssuk-hub-school small{margin-top:5px;color:#718078;font-size:12px}.ssuk-hub-section-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:16px}.ssuk-hub-section-head h2{margin:8px 0 0;font-size:25px}.ssuk-hub-reset{background:#fff;color:#28594f}.ssuk-hub-class{display:flex;justify-content:space-between;gap:20px;border-top:1px solid #dfe8e1;padding:22px 0}.ssuk-hub-class h3{margin:7px 0 6px;font-size:20px}.ssuk-hub-class p{margin:0;color:#718078;font-size:13px}.ssuk-hub-label{color:#5a8476;font-size:11px;font-weight:800}.ssuk-hub-links{display:flex;flex-wrap:wrap;align-content:flex-start;gap:7px;min-width:180px}.ssuk-hub-links a{border:1px solid #b9cdc0;border-radius:7px;padding:8px 10px;color:#28594f;text-decoration:none;font-size:12px;font-weight:700}.ssuk-hub-empty,.ssuk-hub-muted,.ssuk-hub-error{padding:24px;border-radius:8px;background:#fff;border:1px solid #dfe8e1;color:#718078;font-size:13px}.ssuk-hub-error{color:#9c3026;background:#fff0ee}@media(max-width:700px){.ssuk-hub-main{padding:34px 18px}.ssuk-hub-intro h1{font-size:27px}.ssuk-hub-layout{grid-template-columns:1fr;gap:30px}.ssuk-hub-class{display:block}.ssuk-hub-links{margin-top:16px}.ssuk-hub-bar{padding:18px}.ssuk-hub-bar strong{font-size:17px}}";
  document.head.appendChild(css);
  function api(path){return fetch(url+"/rest/v1/"+path,{headers:{apikey:key,Accept:"application/json"}}).then(function(r){if(!r.ok)throw Error();return r.json();});}
  function esc(v){return String(v||"").replace(/[&<>'"]/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c];});}
  var shell=document.createElement("section");shell.id="ssuk-hub-shell";shell.innerHTML='<div class="ssuk-hub-bar"><div><strong>쑥쌤 교육 허브</strong><span>학교와 수업 자료를 한곳에서</span></div><button type="button" data-teacher>선생님 관리</button></div><main class="ssuk-hub-main"><div class="ssuk-hub-intro"><span>SSUK EDUCATION HUB</span><h1>학교를 선택해 수업으로 들어가세요</h1><p>공개된 학교와 수업의 자료, 결과물, 안내 링크를 확인할 수 있습니다.</p></div><div class="ssuk-hub-layout"><aside><h2>학교 선택</h2><div class="ssuk-hub-school-list" data-schools><p class="ssuk-hub-muted">학교 목록을 불러오는 중입니다.</p></div></aside><section class="ssuk-hub-classes"><div class="ssuk-hub-section-head"><div><span>CLASS ARCHIVE</span><h2 data-title>학교를 선택해 주세요</h2></div><button type="button" class="ssuk-hub-reset" data-reset hidden>전체 학교</button></div><div data-classes><div class="ssuk-hub-empty">학교를 선택하면 공개 수업이 표시됩니다.</div></div></section></div></main>';
  root.prepend(shell);
  var schools=shell.querySelector("[data-schools]"), classes=shell.querySelector("[data-classes]"), title=shell.querySelector("[data-title]"), reset=shell.querySelector("[data-reset]");
  api("ssuk_schools?select=id,name,description&is_published=eq.true&order=name.asc").then(function(items){if(!items.length){schools.innerHTML='<p class="ssuk-hub-muted">아직 공개된 학교가 없습니다.</p>';return;}schools.innerHTML=items.map(function(s){return '<button type="button" class="ssuk-hub-school" data-id="'+esc(s.id)+'" data-name="'+esc(s.name)+'"><span>'+esc(s.name)+'</span><small>'+esc(s.description||"공개 수업 보기")+'</small></button>';}).join("");}).catch(function(){schools.innerHTML='<p class="ssuk-hub-error">학교 목록을 불러오지 못했습니다.</p>';});
  schools.addEventListener("click",function(e){var b=e.target.closest("[data-id]");if(!b)return;schools.querySelectorAll(".ssuk-hub-school").forEach(function(x){x.classList.toggle("active",x===b);});title.textContent=b.dataset.name;reset.hidden=false;classes.innerHTML='<div class="ssuk-hub-empty">수업 목록을 불러오는 중입니다.</div>';api("class_boards?select=id,title,description&school_id=eq."+encodeURIComponent(b.dataset.id)+"&hub_published=eq.true&order=created_at.desc").then(function(items){if(!items.length){classes.innerHTML='<div class="ssuk-hub-empty">아직 공개된 수업이 없습니다.</div>';return;}classes.innerHTML=items.map(function(x){return '<article class="ssuk-hub-class"><div><span class="ssuk-hub-label">공개 수업</span><h3>'+esc(x.title)+'</h3><p>'+esc(x.description||"수업 자료와 결과물을 확인하세요.")+'</p></div></article>';}).join("");}).catch(function(){classes.innerHTML='<div class="ssuk-hub-error">수업 목록을 불러오지 못했습니다.</div>';});});
  reset.addEventListener("click",function(){title.textContent="학교를 선택해 주세요";reset.hidden=true;classes.innerHTML='<div class="ssuk-hub-empty">학교를 선택하면 공개 수업이 표시됩니다.</div>';schools.querySelectorAll(".ssuk-hub-school").forEach(function(x){x.classList.remove("active");});});
  shell.querySelector("[data-teacher]").addEventListener("click",function(){shell.remove();});
}());